#
# SPDX-FileCopyrightText: 2026 jvondermarck
# SPDX-License-Identifier: MIT
#

# Disable system actions that conflict with JPro multi-instance
dev.showFPS=false
dev.screenshot=false
dev.profiler=false