name: Build and Comment JAR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build project with Maven
        run: mvn clean package

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: DinosaurExploder-JAR-PR${{ github.event.pull_request.number }}
          path: target/dinosaur-exploder-1.0.jar

      - name: Comment with download link
        uses: gavv/pull-request-artifacts@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: target/dinosaur-exploder-1.0.jar
